# 開発環境用gem
source 'https://rubygems.org'

gem 'fablicop', require: false
gem 'guard'
gem 'guard-rake', git: 'https://github.com/rubyist/guard-rake.git', ref: '3138496c512753bcbc83d13af08b7b5ad0538ee7'
gem 'guard-rubocop'
