load 'bormashino/tasks/bormashino.rake'

require 'fileutils'
require 'uri'

desc 'packしdigestする'
task :default do
  Rake::Task['bormashino:pack'].invoke('--mapdir /gem::../gem/')
  Rake::Task['bormashino:delete_wasms'].invoke(TMP)
  Rake::Task['bormashino:digest'].invoke(TMP)
end
