require 'json'
require 'capybara/cuprite'
require 'capybara/rspec'
require 'capybara-screenshot/rspec'
require 'pry'
require 'rspec/retry'
require 'fileutils'
require 'timeout'
require 'socket'
require 'webrick'

class JSConsoleLogger
  def puts(log)
    src = begin
      JSON.parse(log.strip.sub(/\A.+[ 0-9.▶◀]+\{/, '{'))
    rescue StandardError
      nil
    end
    return unless src

    case src['method']
    when 'Runtime.consoleAPICalled'
      msg = src['params']['args'].map { |a| a['value'] || a['description'] }.join(' ')
      $stdout.puts "BROWSER_CONSOLE: #{msg}"
    when 'Runtime.exceptionThrown'
      details = src['params']['exceptionDetails']
      msg = details['exception'] ? (details['exception']['description'] || details['exception']['value']) : details['text']
      $stdout.puts "BROWSER_EXCEPTION: #{msg}"
    end
  rescue StandardError => e
    $stdout.puts "JSConsoleLogger ERROR: #{e.class}: #{e.message}"
    $stdout.puts "JSConsoleLogger RAW LOG: #{log}"
  end
end

Capybara.default_driver = :cuprite
Capybara.javascript_driver = :cuprite
Capybara.register_driver(:cuprite) do |app|
  Capybara::Cuprite::Driver.new(
    app,
    window_size: [1200, 800],
    browser_options: { 'no-sandbox': nil, 'disable-dev-shm-usage': nil },
    logger: JSConsoleLogger.new,
    headless: true,
    # headless: false,
  )
end
Capybara.save_path = './screenshot/'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of example groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # The settings below are suggested to provide a good initial experience
  # with RSpec, but feel free to customize to your heart's content.
  #   # This allows you to limit a spec run to individual examples or groups
  #   # you care about by tagging them with `:focus` metadata. When nothing
  #   # is tagged with `:focus`, all examples get run. RSpec also provides
  #   # aliases for `it`, `describe`, and `context` that include `:focus`
  #   # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  #   config.filter_run_when_matching :focus
  #
  #   # Allows RSpec to persist some state between runs in order to support
  #   # the `--only-failures` and `--next-failure` CLI options. We recommend
  #   # you configure your source control system to ignore this file.
  #   config.example_status_persistence_file_path = "spec/examples.txt"
  #
  #   # Limits the available syntax to the non-monkey patched syntax that is
  #   # recommended. For more details, see:
  #   # https://relishapp.com/rspec/rspec-core/docs/configuration/zero-monkey-patching-mode
  #   config.disable_monkey_patching!
  #
  #   # This setting enables warnings. It's recommended, but in some cases may
  #   # be too noisy due to issues in dependencies.
  #   config.warnings = true
  #
  #   # Many RSpec users commonly either run the entire suite or an individual
  #   # file, and it's useful to allow more verbose output when running an
  #   # individual spec file.
  #   if config.files_to_run.one?
  #     # Use the documentation formatter for detailed output,
  #     # unless a formatter has already been configured
  #     # (e.g., via a command-line flag).
  #     config.default_formatter = "doc"
  #   end
  #
  #   # Print the 10 slowest examples and example groups at the
  #   # end of the test run, to help surface which examples are running
  #   # particularly slow.
  #   config.profile_examples = 10
  #
  #   # Run specs in random order to surface order dependencies. If you find an
  #   # order dependency and want to debug it, you can fix the order by providing
  #   # the seed, which is printed after each run.
  #   #     --seed 1234
  #   config.order = :random
  #
  #   # Seed global randomization in this process using the `--seed` CLI option.
  #   # Setting this allows you to use `--seed` to deterministically reproduce
  #   # test failures related to randomization by passing the same `--seed` value
  #   # as the one that triggered the failure.
  #   Kernel.srand config.seed

  config.filter_run_excluding rake: true

  config.verbose_retry = true
  config.display_try_failure_messages = true

  config.before(:suite) do
    server_host = '127.0.0.1'
    server_port = 5000
    server_start_timeout = 60

    # Kill any existing processes on the port
    puts "Checking for existing servers on port #{server_port}..."
    begin
      TCPSocket.new(server_host, server_port).close
      puts "Found existing server, killing processes on port #{server_port}..."
      `lsof -ti:#{server_port} | xargs kill -9 2>/dev/null`
      sleep 1
    rescue Errno::ECONNREFUSED, Errno::EADDRNOTAVAIL
      # No server running, which is good
    end

    # Build with parcel first
    puts 'Building with parcel...'
    parcel_bin = File.expand_path('../node_modules/.bin/parcel', __dir__)
    if File.exist?(parcel_bin)
      build_cmd = "#{parcel_bin} build js/index.html --dist-dir tmp/ --no-optimize 2>&1"
      puts "Running: #{build_cmd}"
      build_output = `#{build_cmd}`
      puts build_output
    end

    # Start custom HTTP server with proper MIME type support
    puts "Starting HTTP server on #{server_host}:#{server_port}..."
    server = WEBrick::HTTPServer.new(
      BindAddress: server_host,
      Port: server_port,
      DocumentRoot: File.expand_path('../tmp', __dir__),
      Logger: WEBrick::Log.new(File::NULL),
      AccessLog: [],
    )

    # Add proper MIME type for WASM files
    server.config[:MimeTypes]['wasm'] = 'application/wasm'

    $server_pid = fork do
      server.start
    end

    # Wait for server to be ready
    begin
      Timeout.timeout(server_start_timeout) do
        loop do
          TCPSocket.new(server_host, server_port).close
          break
        rescue Errno::ECONNREFUSED, Errno::EADDRNOTAVAIL
          sleep 0.1
        end
      end
      puts "Server is ready at #{server_host}:#{server_port}"
    rescue Timeout::Error
      Process.kill(:SIGTERM, $server_pid) if $server_pid
      raise "Server failed to start within #{server_start_timeout} seconds"
    end
  end

  config.after(:suite) do
    if $server_pid
      begin
        Process.kill(:SIGTERM, $server_pid)
        Process.wait($server_pid)
      rescue Errno::ESRCH, Errno::ECHILD
        # Process already dead
      end
    end
  end
end
