require: rubocop-rake

inherit_from: config/base_rubocop.yml

AllCops:
  Exclude:
    - "src/bundle/**/*"
    - "node_modules/**/*"
    - "head-wasm32-unknown-wasi-full-js/**/*"
    - "3_2-wasm32-unknown-wasi-full-js/**/*"

RSpec/InstanceVariable:
  Enabled: false

Metrics/AbcSize:
  Max: 24

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/SpecFilePathSuffix:
  Enabled: false

# This code intentionally declares a top-level error class within a stub file.
Style/OneClassPerFile:
  Enabled: false
