# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in bormashino.gemspec
gemspec

gem 'rake', '~> 13.0'

gem 'rspec', '~> 3.0'

gem 'rubocop', '~> 1.66', '>= 1.66.0'

gem 'fablicop', '>= 1.10.2', require: false
gem 'guard'
gem 'guard-rspec', require: false
gem 'guard-rubocop'
gem 'pry'
gem 'rubocop-rails', '2.20.2'
gem 'rubocop-rspec', '3.0.0'

gem 'rubocop-rake', '~> 0.6.0'
