inherit_from: ../gem/config/base_rubocop.yml

AllCops:
  Exclude:
    - 'src/bundle/**/*'
    - 'node_modules/**/*'
    - '3_2-wasm32-unknown-wasi-full-js/**/*'
    - 'rubies/**/*'

RSpec/InstanceVariable:
  Enabled: false

# Logging to stdout in the spec helper is intentional.
RSpec/Output:
  Enabled: false

Metrics/AbcSize:
  Max: 24

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/EmptyClass:
  Enabled: false
