# frozen_string_literal: true

# 開発環境用gem
source 'https://rubygems.org'

gem 'bormashino', path: '../gem/'
gem 'pry'
gem 'rake'
gem 'rspec', '>= 3.0.0'
gem 'rubocop', '~> 1.89'
gem 'rubocop-rspec'

group :test do
  gem 'cuprite', '~> 0.15', '>= 0.15.1'
  gem 'rspec-retry'
end

gem 'capybara-screenshot', '~> 1.0', '>= 1.0.26'
