# frozen_string_literal: true

# 開発環境用gem
source 'https://rubygems.org'

gem 'bormashino', path: '../gem/'
gem 'fablicop', require: false
gem 'guard'
gem 'guard-rake', git: 'https://github.com/rubyist/guard-rake.git', ref: '3138496c512753bcbc83d13af08b7b5ad0538ee7'
gem 'guard-rspec', require: false
gem 'guard-rubocop'
gem 'pry'
gem 'rspec', '>= 3.0.0'

group :test do
  gem 'cuprite'
  gem 'rspec-retry'
end

gem 'capybara-screenshot', '~> 1.0'
