name: Nightly integration test with latest ruby.wasm

on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
  schedule:
    - cron: "10 16 * * *"

jobs:
  app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0-preview1
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Set up Chrome
        uses: keyasuda/setup-chrome@latest

      - name: npm install on npm/
        run: (cd npm && npm i)

      - name: setup test-app
        run: |
          cd test-app
          npm update
          bundle update
          (cd src && bundle update)
          bundle exec rake bormashino:download

      - name: get latest ruby.wasm
        run: |
          cd test-app
          rm -rf head-wasm32-unknown-wasi-full-js
          wget https://github.com/maiha/xq.cr/releases/download/v0.3.0/xq
          chmod u+x xq
          curl -L https://github.com/ruby/ruby.wasm/releases/download/$(curl https://github.com/ruby/ruby.wasm/releases.atom | ./xq .title | tee | head -2 | tail -1 | sed -r 's/^.+>(.+?)<.+$/\1/g')/ruby-head-wasm32-unknown-wasi-full-js.tar.gz | tar xz

      - name: test
        run: |
          cd test-app
          bundle exec rake
          nohup npm run dev &
          sleep 15
          bundle exec rspec
